name: Deploy to Netlify

on:
  push:
    branches:
      - main-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Netlify
      uses: jsmrcaga/action-netlify-deploy@v2.0.0
      with:
        NETLIFY_AUTH_TOKEN: nfp_yCEbccZczsiosBy9FYKdEH6msQfdRtdM3a8d
        NETLIFY_SITE_ID: a4c392c7-1045-429d-bab6-83e8791ae6e6
        NETLIFY_DEPLOY_TO_PROD: true
        build_directory: build/dashboard
        deploy-message: "Automated deployment from GitHub Actions"
        install_command: "echo Skipping installing the dependencies"
        build_command: "echo Skipping building the web files"

    - name: Clear cache
      run: npm cache clean --force
